# Generated by Django 4.2.2 on 2023-06-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'друг',
                'verbose_name_plural': 'друзья',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('kind_activity', models.CharField(blank=True, max_length=200, verbose_name='Вид деятельности')),
                ('open_for_contact', models.BooleanField(default=False, verbose_name='Открыт для контактов')),
                ('projects', models.TextField(blank=True, verbose_name='Проекты')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм ID')),
                ('friends', models.ManyToManyField(through='meetup.Friend', to='meetup.guest')),
            ],
            options={
                'verbose_name': 'посетитель',
                'verbose_name_plural': 'посетители',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('start_at', models.TimeField(null=True, verbose_name='Время начала выстапуления')),
                ('end_at', models.TimeField(blank=True, null=True, verbose_name='Время окончания выступления')),
                ('active', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='meetup.event', verbose_name='Событие')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='meetup.guest', verbose_name='Спикер')),
            ],
            options={
                'verbose_name': 'доклад',
                'verbose_name_plural': 'доклады',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetup.guest')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='meetup.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='meetup.guest'),
        ),
        migrations.AddField(
            model_name='friend',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='meetup.guest'),
        ),
        migrations.CreateModel(
            name='EventGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetup.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetup.guest')),
            ],
            options={
                'verbose_name': 'гость мероприятия',
                'verbose_name_plural': 'гости мероприятия',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(through='meetup.EventGuests', to='meetup.guest'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='meetup.guest', verbose_name='Донатор')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='meetup.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'донат',
                'verbose_name_plural': 'донаты',
            },
        ),
    ]
