# Generated by Django 4.2.2 on 2023-06-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to='meetup.guest', verbose_name='Friends'),
        ),
    ]
