# Generated by Django 4.2.2 on 2023-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_guest_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
    ]
