# Generated by Django 4.2.2 on 2023-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_alter_schedule_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(null=True, verbose_name='Время начала выступления'),
        ),
    ]
