# Generated by Django 4.2.2 on 2023-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_alter_schedule_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема'),
        ),
    ]
