# Generated by Django 4.2.2 on 2023-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='friends', to='meetup.guest', verbose_name='Friends'),
        ),
    ]
