# Generated by Django 4.2.2 on 2023-06-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_alter_guest_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='friends',
        ),
    ]
