# Generated by Django 4.2.2 on 2023-06-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_remove_guest_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='meetup.guest')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='meetup.guest')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='friends',
            field=models.ManyToManyField(through='meetup.Friend', to='meetup.guest'),
        ),
    ]
