# Generated by Django 4.2.2 on 2023-06-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_event_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
    ]
