# Generated by Django 4.2.2 on 2023-06-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_eventguests_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='meetup.guest', verbose_name='Донатор'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='meetup.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetup.guest'),
        ),
        migrations.AlterField(
            model_name='question',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='meetup.schedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='meetup.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='meetup.guest', verbose_name='Спикер'),
        ),
    ]
