# Generated by Django 4.2.2 on 2023-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_alter_donation_guest_alter_donation_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='telegram_id',
            field=models.IntegerField(default=1, max_length=15),
        ),
    ]
