# Generated by Django 4.2.2 on 2023-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0012_alter_guest_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'донат', 'verbose_name_plural': 'донаты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventguests',
            options={'verbose_name': 'гость мероприятия', 'verbose_name_plural': 'гости мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'друг', 'verbose_name_plural': 'друзья'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'посетитель', 'verbose_name_plural': 'посетители'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'доклад', 'verbose_name_plural': 'доклады'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания выступления'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_at',
            field=models.TimeField(null=True, verbose_name='Время начала выстапуления'),
        ),
    ]
